### ISSUE TITLE
关于track2 中baseline dev的测试结果

### ISSUE THREAD

**Issue by rookie0607** [hongfeixue/StutteringSpeechChallenge#1]
您好，方便贴一下dev的测试结果吗

**Comment by hongfeixue** [comment]
Dev:
Overall -> 14.85 % N=95612 C=85106 S=7736 D=2770 I=3692

**Comment by rookie0607** [comment]
> Dev： 总体 -> 14.85 % N=95612 C=85106 S=7736 D=2770 I=3692

多谢

**Comment by rookie0607** [comment]
> Dev： 总体 -> 14.85 % N=95612 C=85106 S=7736 D=2770 I=3692

@hongfeixue 您好，我们的dev似乎不一样，我的字符数只有N=53430。

**Comment by hongfeixue** [comment]
> > Dev： 总体 -> 14.85 % N=95612 C=85106 S=7736 D=2770 I=3692
> 
> @hongfeixue 您好，我们的dev似乎不一样，我的字符数只有N=53430。

dev集有7个说话人，分别为["0022", "0005", "0003", "0035", "0004", "0041", "0006"]，经过处理后应有6624条音频

**Comment by rookie0607** [comment]
> > > Dev： 总体 -> 14.85 % N=95612 C=85106 S=7736 D=2770 I=3692
> > 
> > 
> > @hongfeixue 您好，我们的dev似乎不一样，我的字符数只有N=53430。
> 
> dev集有7个说话人，分别为["0022", "0005", "0003", "0035", "0004", "0041", "0006"]，经过处理后应有6624条音频
> > 
> > 
@hongfeixue 我确定使用baseline prepare_data.sh处理后只有3903条数据，你也是通过prepare_data.sh处理的吗？数据处理脚本会不会有一些问题呢

**Comment by Fengzhijjin** [comment]
@hongfeixue 我在task1中的数据处理也遇到了数量不符的问题，你们给出的markdown中显示会得到41953条数据，但我只得到了26659条数据，使用sed/stutter_event/run.sh进行处理

**Comment by hongfeixue** [comment]
> @hongfeixue 我在task1中的数据处理也遇到了数量不符的问题，你们给出的markdown中显示会得到41953条数据，但我只得到了26659条数据，使用sed/stutter_event/run.sh进行处理

这个没有问题，train集是26659的

**Comment by rookie0607** [comment]
> > @hongfeixue我在task1中的数据处理也遇到了数量不符的问题，你们给出的markdown中显示会得到41953条数据，但我只得到26659条，使用sed/stutter_event/run.sh进行处理
> 
> 这个没有问题，trainset是26659的

@hongfeixue track2 trainset处理后是23435条嘛

**Comment by hongfeixue** [comment]
> > > @hongfeixue我在task1中的数据处理也遇到了数量不符的问题，你们给出的markdown中显示会得到41953条数据，但我只得到26659条，使用sed/stutter_event/run.sh进行处理
> > 
> > 
> > 这个没有问题，trainset是26659的
> 
> @hongfeixue track2 trainset处理后是23435条嘛

@rookie0607 应该是32336条，可能存在一些问题，我检查一下

**Comment by Fengzhijjin** [comment]
>

> > @hongfeixue 我在task1中的数据处理也遇到了数量不符的问题，你们给出的markdown中显示会得到41953条数据，但我只得到了26659条数据，使用sed/stutter_event/run.sh进行处理
> 
> 这个没有问题，train集是26659的

好的，感谢

**Comment by hongfeixue** [comment]
@rookie0607 可以继续使用现有数据进行训练和验证，我会以现有数据重新跑一个baseline

**Comment by rookie0607** [comment]
> @rookie0607可以继续使用现有数据进行训练和验证，我会以现有数据重新运行一个基线

好的，另外我发现了验证集上有一些标注错误，后面会拉一个微信群交流吗

**Comment by MisakiWho** [comment]
> > @hongfeixue

我按照prepare_data.sh处理后，dev是3903条，train是22866条。

**Comment by hongfeixue** [comment]
> > > @hongfeixue
> 
> 我按照prepare_data.sh处理后，dev是3903条，train是22866条。

@MisakiWho 没问题，脚本处理后是这样的

**Comment by hongfeixue** [comment]
> > @rookie0607可以继续使用现有数据进行训练和验证，我会以现有数据重新运行一个基线
> 
> 好的，另外我发现了验证集上有一些标注错误，后面会拉一个微信群交流吗

@rookie0607 感谢建议，微信群我们会考虑建一个的

**Comment by rookie0607** [comment]
@hongfeixue 你好，结果更新了吗

**Comment by hongfeixue** [comment]
@rookie0607 dev是3903条，结果为 Overall -> 13.32 % N=53322 C=47972 S=3901 D=1449 I=1751
