### ISSUE TITLE
关于task1  baseline  dev测试结果

### ISSUE THREAD

**Issue by tt-njupt** [hongfeixue/StutteringSpeechChallenge#2]
请问，为什么按照run.sh启动，复现的结果比给出的结果差？

**Comment by hongfeixue** [comment]
sed/examples/stutter_event/s0/wenet/bin/infer_sed.py:133，可以调整threshold寻找最优结果

**Comment by tt-njupt** [comment]
![QQ截图20240511171443](https://github.com/hongfeixue/StutteringSpeechChallenge/assets/113867489/ad17b321-1962-4419-9aeb-72f8d560e5a2)
有的指标的，精确率和召回率都低于基线结果，调整threshold应该没有效果吧

**Comment by hongfeixue** [comment]
@tt-njupt 调整threshold让Rec和Prec的值更接近，F1会提高的。/b的34和41就差的比较多，/r的27和44差的更多，/wr的53和70，可以在解码时稍微增大或减小对应的threshold。

**Comment by hongfeixue** [comment]
@tt-njupt 此外，我们使用的4*3090训练100 epoch，可以对应一下梯度累计
